const DATA=[
// ── LÍNGUA PORTUGUESA ──
{cat:'port',id:'pt-2',num:'2',t:'Tipos e gêneros textuais',b:'<b>Tipos textuais</b> = estrutura interna (narrativo, descritivo, dissertativo, injuntivo). <b>Gêneros textuais</b> = formas concretas de circulação (e-mails, receitas, notícias, contos). Tipo → organização estrutural. Gênero → finalidade sociointerativa.'},
{cat:'port',id:'pt-3',num:'3',t:'Domínio da ortografia',b:'Uso correto de letras (s, z, x, ch, g, j), <b>acentuação gráfica</b> conforme o Acordo Ortográfico e <b>emprego do hífen</b>.'},
{cat:'port',id:'pt-4',num:'4',t:'Mecanismos de coesão textual',b:'<ul><li><b>Coesão Referencial:</b> pronomes, sinônimos, elipses para retomar (anáfora) ou antecipar (catáfora) termos.</li><li><b>Coesão Sequencial:</b> conectivos para relações lógicas (causa, condição, tempo, oposição).</li><li><b>Estratégias:</b> substituição lexical, omissão, tempos verbais adequados, pontuação correta.</li></ul>'},
{cat:'port',id:'pt-4.1',num:'4.1',t:'Referenciação, substituição, conectores e sequenciação',b:'Uso de pronomes e sinônimos para evitar repetições (<b>referenciação</b> e <b>substituição</b>). Emprego de conjunções e advérbios para relações lógicas e sequência entre ideias.'},
{cat:'port',id:'pt-4.2',num:'4.2',t:'Emprego de tempos e modos verbais',b:'Flexão dos verbos para indicar o momento (presente, pretérito, futuro) e a atitude (certeza = <b>indicativo</b>, dúvida = <b>subjuntivo</b>, ordem = <b>imperativo</b>). Correlação verbal. Formas nominais: infinitivo, gerúndio e particípio.'},
{cat:'port',id:'pt-5.1',num:'5.1',t:'Emprego das classes de palavras',b:'10 categorias: <b>substantivo, artigo, adjetivo, numeral, pronome, verbo, advérbio, preposição, conjunção, interjeição</b>. Flexão em gênero, número, tempo ou pessoa.'},
{cat:'port',id:'pt-5.2',num:'5.2',t:'Coordenação entre orações',b:'Orações independentes (sentido completo):<ul><li><b>Assindéticas:</b> sem conjunção (Vim, vi, venci)</li><li><b>Aditivas:</b> e, nem, não só... mas também</li><li><b>Adversativas:</b> mas, porém, contudo, todavia</li><li><b>Alternativas:</b> ou, ora... ora, quer... quer</li><li><b>Conclusivas:</b> logo, portanto, por isso, pois (após verbo)</li><li><b>Explicativas:</b> porque, que, pois (antes do verbo)</li></ul>'},
{cat:'port',id:'pt-5.3',num:'5.3',t:'Subordinação entre orações',b:'Oração exerce função sintática em relação a outra (dependência hierárquica):<ul><li><b>Substantivas:</b> sujeito, objeto, complemento</li><li><b>Adjetivas:</b> restringem ou explicam substantivo</li><li><b>Adverbiais:</b> tempo, causa, condição, finalidade, consequência</li></ul>'},
{cat:'port',id:'pt-5.4',num:'5.4',t:'Sinais de pontuação',b:'<ul><li><b>Vírgula:</b> pausas, enumerações, vocativos, apostos. NÃO separa sujeito-verbo.</li><li><b>Ponto e vírgula:</b> pausa intermediária</li><li><b>Dois-pontos:</b> explicações, citações, enumerações</li><li><b>Travessão:</b> diálogos ou termos explicativos</li><li><b>Aspas:</b> citações, gírias, neologismos</li><li><b>Reticências:</b> interrupção/hesitação</li></ul>'},
{cat:'port',id:'pt-5.5',num:'5.5',t:'Concordância verbal e nominal',b:'<b>Verbal:</b> harmonia entre verbo e sujeito. <b>Nominal:</b> harmonia entre substantivo e seus modificadores (adjetivos, artigos).'},
{cat:'port',id:'pt-5.6',num:'5.6',t:'Regência verbal e nominal',b:'<b>Verbal:</b> relação verbo → complemento (com ou sem preposição). Ex: aspirar <b>a</b> algo (desejar) vs aspirar algo (respirar). <b>Nominal:</b> nome → complemento (obrigatoriamente com preposição). Ex: apto <b>a</b>, ansioso <b>por</b>.'},
{cat:'port',id:'pt-5.7',num:'5.7',t:'Emprego da crase',b:'Fusão de preposição "a" + artigo "a(s)" ou demonstrativos.<ul><li><b>Obrigatória:</b> palavras femininas com artigo, expressões adverbiais femininas, horas exatas.</li><li><b>Proibida:</b> diante de masculinas, verbos, numerais, pronomes pessoais.</li><li><b>Facultativa:</b> nomes próprios femininos, possessivos femininos singulares, após "até".</li></ul>'},
{cat:'port',id:'pt-5.8',num:'5.8',t:'Colocação pronominal',b:'<b>Próclise</b> (antes): palavras atrativas (negativas, advérbios, pronomes relativos). <b>Mesóclise</b> (meio): futuro do presente/pretérito. <b>Ênclise</b> (depois): início de frase, imperativo afirmativo.'},
{cat:'port',id:'pt-6',num:'6',t:'Reescrita de frases e parágrafos',b:'Alterar estrutura mantendo sentido e correção. Inclui significação (sinonímia, antonímia, homonímia, paronímia, denotação, conotação), substituição de palavras/trechos e reorganização sintática.'},

// ── LÍNGUA INGLESA ──
{cat:'eng',id:'en-1',num:'1',t:'Compreensão de textos variados',b:'Identificação de teses centrais e argumentos secundários. Estudo de conectivos para relações de <b>causa</b>, <b>consequência</b> e <b>oposição</b>. Ideias explícitas e implícitas. Relações intratextuais e intertextuais.'},
{cat:'eng',id:'en-2',num:'2',t:'Itens gramaticais relevantes para semântica',b:'Classes de palavras, tempos verbais, pronomes, conjunções e estruturas sintáticas para identificar sentido, propósito e relações lógicas em textos em inglês.'},
{cat:'eng',id:'en-3',num:'3',t:'Formas contemporâneas da linguagem inglesa',b:'<ul><li>Neologismos: doomscrolling, hangry</li><li>Internetês e gírias: FOMO, YOLO</li><li>Linguagem inclusiva: they/them singular</li><li>Termos tech como verbos: to Google, to Zoom</li><li>Inglês como língua global e multicultural</li></ul>'},

// ── RACIOCÍNIO LÓGICO ──
{cat:'logic',id:'rl-1',num:'1',t:'Estruturas lógicas',b:'Proposição: sentença declarativa, V ou F. Proposições simples e compostas. <b>Conectivos:</b> e, ou, se...então, se e somente se. <b>Tabelas-verdade.</b> Princípios: não contradição e terceiro excluído.'},
{cat:'logic',id:'rl-2',num:'2',t:'Lógica de argumentação',b:'<ul><li><b>Dedução:</b> conclusão necessária de leis gerais</li><li><b>Indução:</b> generalização de observações específicas</li><li><b>Analogia:</b> conclusão por semelhança</li><li><b>Inferência:</b> derivar proposições de dados conhecidos</li></ul>'},
{cat:'logic',id:'rl-3',num:'3',t:'Lógica sentencial (proposicional)',b:'Estuda proposições e combinações via conectivos. Símbolos para afirmações. Tabelas-verdade para validade.'},
{cat:'logic',id:'rl-3.2',num:'3.2',t:'Tabelas-verdade',b:'Todos os valores lógicos possíveis de uma proposição composta. Conectivos: negação, conjunção, disjunção, condicional, bicondicional. Linhas = <b>2ⁿ</b> (n = proposições simples).'},
{cat:'logic',id:'rl-3.3',num:'3.3',t:'Equivalências lógicas',b:'<ul><li><b>Contrapositiva:</b> P→Q ≡ ~Q→~P</li><li><b>Condicional→Disjunção:</b> P→Q ≡ ~P∨Q</li><li><b>Dupla Negação:</b> ~~P ≡ P</li><li><b>De Morgan:</b> ~(P∧Q) ≡ ~P∨~Q / ~(P∨Q) ≡ ~P∧~Q</li><li><b>Comutatividade</b></li></ul>'},
{cat:'logic',id:'rl-3.5',num:'3.5',t:'Diagramas lógicos',b:'Diagramas de Venn: representação gráfica de relações entre conjuntos. Proposições categóricas: <b>Todo</b>, <b>Algum</b>, <b>Nenhum</b>. Interseções, uniões, inclusões.'},
{cat:'logic',id:'rl-4',num:'4',t:'Lógica de primeira ordem',b:'Extensão da lógica proposicional. <b>Predicados</b> (propriedades/relações). <b>Quantificadores:</b> universal (∀) e existencial (∃). Variáveis, constantes e funções. Maior expressividade para formalizar sentenças complexas.'},
{cat:'logic',id:'rl-5',num:'5',t:'Contagem e probabilidade',b:'<b>PFC:</b> n × m possibilidades. <b>Probabilidade:</b> favoráveis ÷ total. Base da análise combinatória.'},
{cat:'logic',id:'rl-6',num:'6',t:'Operações com conjuntos',b:'<ul><li><b>União:</b> pelo menos um conjunto</li><li><b>Interseção:</b> todos os conjuntos</li><li><b>Diferença:</b> em um, não no outro</li><li><b>Complementar:</b> universo − conjunto</li><li><b>Produto Cartesiano:</b> pares ordenados</li></ul>'},
{cat:'logic',id:'rl-8',num:'8',t:'Estatística básica',b:'<ul><li><b>Tendência central:</b> média, mediana, moda</li><li><b>Dispersão:</b> amplitude, variância, desvio padrão, coeficiente de variação</li><li><b>Hipóteses:</b> H₀ e H₁, nível de significância</li><li><b>Amostragem:</b> erro amostral vs viés</li><li><b>Normalização:</b> [0,1]. <b>Padronização:</b> z-score (μ=0, σ=1)</li><li><b>Outliers:</b> pontos fora da curva, Boxplot</li></ul>'},

// ── DIREITO CONSTITUCIONAL ──
{cat:'const',id:'dc-1',num:'1',t:'CF/88: conceito e estrutura',b:'Lei fundamental do Brasil, promulgada em 05/10/1988. <b>Constituição Cidadã.</b> Características: analítica, formal, dirigente, rígida. Estrutura: Preâmbulo + 9 Títulos (250 artigos) + ADCT.'},
{cat:'const',id:'dc-2',num:'2',t:'Princípios fundamentais (Arts. 1º-4º)',b:'Fundamentos da República: <b>soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e livre iniciativa, pluralismo político</b>. Separação dos Poderes. Objetivos fundamentais. Relações internacionais.'},
{cat:'const',id:'dc-3',num:'3',t:'Direitos e garantias fundamentais',b:'Título II (Arts. 5º-17):<ul><li><b>Art. 5º:</b> individuais e coletivos, remédios constitucionais</li><li><b>Arts. 6º-11:</b> direitos sociais</li><li><b>Arts. 12-13:</b> nacionalidade (natos vs naturalizados)</li><li><b>Arts. 14-16:</b> direitos políticos, elegibilidade</li><li><b>Art. 17:</b> partidos políticos</li></ul>'},
{cat:'const',id:'dc-4',num:'4',t:'Organização do Estado',b:'Entes autônomos: União, Estados, DF, Municípios (Art. 18). Repartição de competências e rendas. Brasília = Capital Federal. <b>Intervenção Federal</b> (Arts. 34-36): mecanismo excepcional e temporário, decreto do Presidente, submetido ao CN em 24h.'},
{cat:'const',id:'dc-5',num:'5',t:'Administração pública (Arts. 37-41)',b:'Princípios: <b>LIMPE</b> (Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência). Concursos, cargos em comissão, funções de confiança. Servidores civis: remuneração, <b>estabilidade</b> (3 anos), aposentadoria. Art. 42: militares estaduais.'},
{cat:'const',id:'dc-6',num:'6',t:'Poder Legislativo e Congresso Nacional',b:'Bicameral: Câmara (povo) + Senado (Estados/DF).<ul><li><b>Art. 48:</b> competência com sanção presidencial</li><li><b>Art. 49:</b> competência exclusiva (decreto legislativo)</li><li><b>Art. 51:</b> atribuições da Câmara</li><li><b>Art. 52:</b> atribuições do Senado</li></ul>Comissões permanentes e CPIs. TCU auxilia fiscalização.'},
{cat:'const',id:'dc-7',num:'7',t:'Regime dos parlamentares (Arts. 53-56)',b:'<ul><li><b>Imunidade material:</b> inviolabilidade por opiniões/votos</li><li><b>Imunidade formal:</b> foro no STF, prisão só flagrante inafiançável</li><li><b>Vedações:</b> Art. 54 — contratos com entes públicos</li><li><b>Perda do mandato:</b> Art. 55 — quebra de decoro, condenação</li><li><b>Licenças:</b> Art. 56 — Ministro, Secretário, saúde</li></ul>'},
{cat:'const',id:'dc-8',num:'8',t:'Processo legislativo',b:'Atos para elaboração de normas: emendas à CF, leis complementares/ordinárias, medidas provisórias, decretos legislativos, resoluções. Fases: iniciativa → comissões → votação → sanção/veto → promulgação.'},
{cat:'const',id:'dc-9',num:'9',t:'Defesa do Estado e instituições democráticas',b:'Arts. 136-144 CF. <b>Estado de Defesa</b> e <b>Estado de Sítio</b> (medidas excepcionais e temporárias). <b>Forças Armadas:</b> Marinha, Exército, Aeronáutica — vedadas sindicalização e greve. <b>Segurança Pública</b> (Art. 144): PF, PRF, PFF, PC, PM, CBM, Polícias Penais.'},

// ── LEGISLAÇÃO CÂMARA ──
{cat:'ricd',id:'ri-12',num:'12',t:'Regimento Interno da Câmara (Res. 17/1989)',b:'Normas de funcionamento administrativo e processo legislativo. 29ª edição (até Res. 16/2025). Inclui Código de Ética e Regimento Comum do CN.'},
{cat:'ricd',id:'ri-12.1',num:'12.1',t:'Disposições preliminares e órgãos (Arts. 1º-24)',b:'Sede na Capital Federal. <b>Mesa Diretora:</b> Presidente + 2 Vice + 4 Secretários. <b>Colégio de Líderes</b> e lideranças partidárias.'},
{cat:'ricd',id:'ri-12.2',num:'12.2',t:'Sessões da Câmara (Arts. 226-251)',b:'Tipos: preparatórias, deliberativas (ordinárias/extraordinárias), não deliberativas, solenes. Quórum, ordem do dia, uso da palavra, ata. Urgência e votações (simbólica/nominal).'},
{cat:'ricd',id:'ri-12.4',num:'12.4',t:'Administração e economia interna (Arts. 262-273)',b:'Art. 262: serviços administrativos regidos por regulamentos da Mesa. Art. 273: proibido comércio sem autorização. Art. 274: delegação de competência.'},
{cat:'ricd',id:'ri-13',num:'13',t:'Resolução 18/2003 e Ato 234/2025 – Depol',b:'Departamento de Polícia Legislativa Federal. Cargos: Analista (Inspetor) e Técnico (Agente) de Segurança Legislativa. Competências: policiamento, segurança de bens e pessoas, controle de acesso, fiscalização de trânsito, mandados judiciais.'},

// ── DIREITO ADMINISTRATIVO ──
{cat:'admin',id:'da-1',num:'1',t:'Organização administrativa',b:'<ul><li><b>Administração Direta:</b> órgãos ligados à Presidência/Ministérios (centralizada)</li><li><b>Administração Indireta:</b> autarquias, fundações, empresas públicas, SEM</li><li><b>Centralização:</b> Estado executa diretamente</li><li><b>Descentralização:</b> transfere para outras pessoas</li><li><b>Desconcentração:</b> distribuição interna em uma mesma PJ</li></ul>'},
{cat:'admin',id:'da-1.3',num:'1.3',t:'Autarquias, fundações, EP e SEM',b:'<ul><li><b>Autarquias:</b> PJ dir. público, criadas por lei, atividades típicas de Estado</li><li><b>Fundações:</b> interesse social, dir. público ou privado</li><li><b>Empresas Públicas:</b> dir. privado, capital 100% público</li><li><b>SEM:</b> dir. privado, capital misto, forma de S.A.</li></ul>'},
{cat:'admin',id:'da-2',num:'2',t:'Ato administrativo',b:'Manifestação unilateral da Adm. Pública.<br><b>Requisitos:</b> competência, finalidade, forma, motivo, objeto.<br><b>Atributos:</b> presunção de legitimidade, imperatividade, autoexecutoriedade, tipicidade.<br><b>Classificação:</b> gerais/individuais, internos/externos, vinculados/discricionários.<br><b>Anulação:</b> ilegal, efeitos <b>ex tunc</b>. <b>Revogação:</b> conveniência, efeitos <b>ex nunc</b>.'},
{cat:'admin',id:'da-3',num:'3',t:'Agentes públicos',b:'Toda pessoa física com função pública. Espécies: políticos, administrativos, honoríficos, delegados, credenciados.<br><b>Cargo público:</b> criado por lei, efetivo ou comissão.<br><b>Emprego público:</b> CLT.<br><b>Função pública:</b> temporários ou funções de confiança.<br>Base: Lei 8.112/1990, Arts. 37-41 CF.'},
{cat:'admin',id:'da-3.5',num:'3.5',t:'Regime dos servidores federais (Lei 8.112/1990)',b:'<b>Direitos:</b> estabilidade (3 anos), irredutibilidade, licenças, aposentadoria, férias, 13º.<br><b>Deveres:</b> zelo, lealdade, normas legais, presteza, ética.<br><b>Responsabilidades:</b> civil + penal + administrativa (independentes). PAD → advertência/suspensão/demissão.'},
{cat:'admin',id:'da-4',num:'4',t:'Direito administrativo disciplinar',b:'Poder de apurar infrações e aplicar sanções. Base: poder hierárquico + devido processo legal. <b>PAD:</b> instauração → instrução → defesa → relatório → julgamento. <b>LIMPE</b> como princípios fundamentais (Art. 37 CF).'},
{cat:'admin',id:'da-5',num:'5',t:'Poderes administrativos',b:'<ul><li><b>Hierárquico:</b> organizar, coordenar, fiscalizar</li><li><b>Disciplinar:</b> apurar infrações, aplicar penalidades</li><li><b>Regulamentar:</b> decretos/regulamentos para execução de leis</li><li><b>De Polícia:</b> restringe direitos individuais pelo bem comum</li><li><b>Vinculado:</b> sem margem de escolha</li><li><b>Discricionário:</b> conveniência e oportunidade</li></ul><b>Abuso de poder:</b> excesso (vício de competência) ou desvio de finalidade.'},
{cat:'admin',id:'da-6',num:'6',t:'Controle da administração pública',b:'<ul><li><b>Administrativo (autotutela):</b> anular ilegais, revogar inconvenientes</li><li><b>Judicial:</b> legalidade/constitucionalidade. Jurisdição única (Art. 5º XXXV). Mérito discricionário: em regra vedado.</li><li><b>Legislativo:</b> controle político (CPIs, convocações) + financeiro (TCU)</li></ul>'},
{cat:'admin',id:'da-7',num:'7',t:'Responsabilidade civil do Estado',b:'Art. 37 §6º CF. <b>Objetiva</b> (risco administrativo): conduta + dano + nexo causal. <b>Subjetiva</b> (omissão): exige culpa (faute du service).<br><b>Excludentes:</b> culpa exclusiva da vítima, caso fortuito/força maior, ato de terceiro.<br><b>Atenuante:</b> culpa concorrente → redução proporcional.<br><b>Regresso:</b> contra o agente por dolo/culpa.'},
{cat:'admin',id:'da-8',num:'8',t:'Improbidade Administrativa (Lei 8.429/1992)',b:'<ul><li><b>Enriquecimento ilícito</b></li><li><b>Prejuízo ao erário</b> (dolo)</li><li><b>Atos contra princípios da administração</b></li></ul>Sanções: perda da função, suspensão de direitos políticos, multa, proibição de contratar. <b>Lei 14.230/2021:</b> exige <b>dolo</b>.'},
{cat:'admin',id:'da-9',num:'9',t:'Lei de Acesso à Informação (Lei 12.527/2011)',b:'Publicidade = regra. Sigilo = exceção. <b>Transparência ativa</b> (divulgação espontânea) e <b>passiva</b> (atendimento a solicitações).'},
{cat:'admin',id:'da-10',num:'10',t:'LGPD (Lei 13.709/2018)',b:'Tratamento de dados pessoais para proteger liberdade, privacidade e livre desenvolvimento da personalidade. Regras para coleta, armazenamento e compartilhamento.'},
{cat:'admin',id:'da-11',num:'11',t:'Bens públicos',b:'Art. 98 CC. Regime: <b>inalienabilidade</b>, <b>impenhorabilidade</b>, <b>imprescritibilidade</b> (sem usucapião).<ul><li><b>Uso comum:</b> ruas, praças, rios</li><li><b>Uso especial:</b> hospitais, escolas, repartições</li><li><b>Dominicais:</b> patrimônio disponível, alienáveis</li></ul>'},
{cat:'admin',id:'da-12',num:'12',t:'LINDB (Lei 4.657/1942) – regime administrativo',b:'Após Lei 13.655/2018: decisões baseadas em <b>consequências práticas</b> (Art. 20). Dever de motivação clara. Regimes de transição (Art. 23). Proteção da confiança legítima (Art. 24). Segurança jurídica.'},
{cat:'admin',id:'da-13',num:'13',t:'Licitações e Contratos (Lei 14.133/2021)',b:'Substituiu Leis 8.666/93, Pregão e RDC. <b>Modalidades:</b> pregão, concorrência, concurso, leilão, diálogo competitivo. <b>PNCP</b>.<br><b>Dispensa:</b> licitação viável mas desobrigada. <b>Inexigibilidade:</b> competição inviável.<br><b>Contratos:</b> cláusulas exorbitantes, intuitu personae. Alterações unilaterais: <b>25%</b> (geral) / <b>50%</b> (reformas). Fiscal + preposto.<br>Matriz de riscos para equilíbrio econômico-financeiro.'},
{cat:'admin',id:'da-14',num:'14',t:'Administração Orçamentária e Financeira',b:'Instrumentos: <b>PPA</b>, <b>LDO</b>, <b>LOA</b>. Execução da despesa: <b>empenho</b> (reserva) → <b>liquidação</b> (verificação) → <b>pagamento</b> (ordem bancária). Pré-empenho = reserva preventiva opcional.<br><b>Restos a Pagar:</b> processados (liquidados) e não processados. <b>DEA:</b> obrigações de exercícios anteriores sem empenho.<br><b>Suprimento de fundos:</b> adiantamento a servidor, CPGF, prazo certo, vedado a servidor em alcance.'},

// ── INFORMÁTICA E DADOS ──
{cat:'info',id:'if-1',num:'1',t:'Sistemas operacionais: Windows, Android, iOS',b:'<b>Windows:</b> desktops, interface gráfica, multitarefa. <b>Android:</b> Google, baseado em Linux, touch. <b>iOS:</b> Apple, fechado, iPhones, integração e segurança.'},
{cat:'info',id:'if-2',num:'2',t:'Navegadores, webmail e ferramentas de produtividade',b:'Chrome, Firefox. E-mail via web. Google Workspace, Microsoft 365.'},
{cat:'info',id:'if-3',num:'3',t:'Segurança da informação',b:'Pilares: <b>confidencialidade</b>, <b>integridade</b>, <b>disponibilidade</b>, autenticidade. Deveres dos usuários: uso ético, cumprir políticas, proteger informações, reportar irregularidades.'},
{cat:'info',id:'if-3.2',num:'3.2',t:'Malware',b:'<ul><li><b>Vírus:</b> depende de execução do usuário</li><li><b>Worms:</b> autorreplicantes via rede</li><li><b>Trojans:</b> disfarçados de software legítimo</li><li><b>Spyware:</b> coleta dados secretamente</li><li><b>Ransomware:</b> criptografa e exige resgate</li><li><b>Backdoor:</b> acesso remoto permanente</li><li><b>Zero-day:</b> vulnerabilidades desconhecidas</li><li><b>Keyloggers:</b> registram teclas</li></ul>'},
{cat:'info',id:'if-3.3',num:'3.3',t:'Phishing, vishing e engenharia social',b:'<b>Engenharia social:</b> manipulação psicológica (confiança, medo, urgência).<br><b>Phishing:</b> e-mail com links/anexos maliciosos.<br><b>Vishing:</b> phishing por telefone/voz.<br><b>Smishing:</b> SMS. Canais: e-mail, telefone, SMS, redes sociais.'},
{cat:'info',id:'if-3.4',num:'3.4',t:'Aplicativos de segurança',b:'Antivírus, <b>EDR</b> (Endpoint Detection and Response), firewall, anti-spyware, gerenciadores de senhas.'},
{cat:'info',id:'if-3.5',num:'3.5',t:'Assinatura e certificação digital',b:'<b>Certificado Digital:</b> identidade virtual (e-CPF/e-CNPJ). Emitido por AC da ICP-Brasil. Criptografia assimétrica. A1 (software, 1 ano) e A3 (token, 3 anos).<br><b>Assinatura Digital:</b> integridade + autenticidade, validade jurídica.<br><b>Assinatura Eletrônica</b> (Lei 14.063/20): simples, avançada, qualificada (ICP-Brasil).'},
{cat:'info',id:'if-4',num:'4',t:'Bancos de dados',b:'Coleção organizada de informações. Modelos: relacional (tabelas) ou NoSQL. Gerenciado por SGBD. <b>Dados estruturados:</b> tabelas, SQL. <b>Não estruturados:</b> texto, imagens, vídeo. <b>Chave primária:</b> identificador único. <b>Chave estrangeira:</b> vínculo entre tabelas. Relacionamentos: 1:1, 1:N, N:N.'},
{cat:'info',id:'if-5',num:'5',t:'Redes de computadores',b:'<ul><li><b>LAN:</b> rede local (alta velocidade, baixa latência)</li><li><b>MAN:</b> metropolitana (cidade/campus)</li><li><b>WAN:</b> longa distância (Internet)</li></ul><b>Internet:</b> global, TCP/IP, pública. <b>Intranet:</b> privada. <b>Extranet:</b> acesso externo controlado.<br><b>TCP/IP:</b> 4 camadas. <b>NAT:</b> tradução de IP privado→público. <b>VPN:</b> túnel seguro. <b>RDP:</b> controle remoto (porta 3389).'},
{cat:'info',id:'if-6',num:'6',t:'Aprendizado de máquina e IA',b:'<b>ML:</b> supervisionado, não supervisionado, por reforço. <b>Mineração de dados:</b> padrões em grandes volumes (KDD).<br><b>Big Data:</b> 5 Vs (Volume, Velocidade, Variedade, Veracidade, Valor).<br><b>IA Generativa:</b> LLMs, GANs, VAEs — criação de conteúdo original.'},
{cat:'info',id:'if-7',num:'7',t:'Forense computacional',b:'Identificar, preservar, recuperar e analisar evidências digitais.<br><b>Recuperação:</b> lixeira, metadados, softwares (Recuva, R-Studio), <b>carving</b> (headers/footers), shadow copy, imagem forense (bit a bit).<br><b>Vestígios cibernéticos:</b> identificação → isolamento → preservação → coleta.<br><b>Cadeia de custódia:</b> Arts. 158-A a 158-F CPP. Hash + metadados. 10 etapas.<br><b>Log do Windows:</b> Sistema, Aplicativo, Segurança, Instalação.'}
];

const CATS={
  port:{icon:'fa-book',title:'Língua Portuguesa',color:'#059669'},
  eng:{icon:'fa-language',title:'Língua Inglesa',color:'#0891b2'},
  logic:{icon:'fa-brain',title:'Raciocínio Lógico e Estatística',color:'#7c3aed'},
  const:{icon:'fa-landmark',title:'Direito Constitucional',color:'#ea580c'},
  ricd:{icon:'fa-building-columns',title:'Legislação Interna da Câmara',color:'#b45309'},
  admin:{icon:'fa-briefcase',title:'Direito Administrativo',color:'#dc2626'},
  info:{icon:'fa-laptop-code',title:'Informática e Dados',color:'#2563eb'}
};
