// ═══════════════════════════════════════════════════════════
// SIMULADO FINAL – BANCO DE QUESTÕES (180 itens C/E)
// Policial Legislativo CD 2026 – Baseado CEBRASPE 2022-2025
// ═══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────
// CONHECIMENTOS GERAIS (90 itens)
// Português(15) + Inglês(15) + RLM(15) + Constitucional(15) + Administrativo(15) + Informática(15)
// ──────────────────────────────────────────────────────
const CG = [
// ── LÍNGUA PORTUGUESA (1-15) ──
{n:1,t:'Português – Interpretação',q:'Na interpretação de textos, a <b>compreensão</b> exige que a informação esteja explícita no texto, enquanto a <b>interpretação</b> permite inferências a partir do que está escrito.',a:true,e:'Compreensão = explícito no texto. Interpretação = inferência (leitura nas entrelinhas). Distinção clássica CEBRASPE.'},
{n:2,t:'Português – Coesão',q:'Na frase "O deputado apresentou o projeto; <b>este</b> foi aprovado", o pronome "este" exerce função <b>anafórica</b>, retomando "projeto".',a:true,e:'"Este" retoma o termo mais próximo (projeto). Anáfora = retoma algo já mencionado. Catáfora = antecipa algo.'},
{n:3,t:'Português – Pontuação',q:'Na ordem direta (S-V-C), é permitido o uso de vírgula entre o <b>sujeito e o verbo</b> para dar ênfase ou clareza.',a:false,e:'NUNCA se separa sujeito-verbo-complemento na ordem direta com vírgula. Regra absoluta, sem exceção.'},
{n:4,t:'Português – Concordância',q:'O verbo <b>"haver"</b> no sentido de "existir" é impessoal e permanece na <b>3ª pessoa do singular</b>.',a:true,e:'"Havia muitos candidatos" (singular). Haver=existir → impessoal. Existir é pessoal: "Existiam candidatos".'},
{n:5,t:'Português – Crase',q:'Na frase "O policial se dirigiu <b>à</b> delegacia", o acento grave é obrigatório: preposição "a" + artigo feminino "a".',a:true,e:'Dirigir-se A + A delegacia = à. Teste: substitua por masculino → "ao quartel" confirma crase.'},
{n:6,t:'Português – SE apassivador',q:'Em "Vendem-se casas", o <b>SE</b> é índice de indeterminação do sujeito e o verbo deveria ficar no singular.',a:false,e:'VTD + SE = partícula apassivadora. "Casas" = sujeito paciente → verbo no plural. SE indeterminador: VTI/VI.'},
{n:7,t:'Português – Regência',q:'O verbo <b>"implicar"</b> no sentido de acarretar é transitivo direto: "A decisão <b>implica</b> mudanças" (sem preposição).',a:true,e:'"Implica mudanças" ✅ (VTD). "Implica em mudanças" ❌. CEBRASPE cobra a regência formal.'},
{n:8,t:'Português – Conjunção',q:'A conjunção <b>"embora"</b> tem valor concessivo e exige verbo no modo <b>subjuntivo</b>.',a:true,e:'Embora/conquanto/ainda que + subjuntivo. "Embora estude" ✅. "Embora estuda" ❌.'},
{n:9,t:'Português – Conectivos',q:'Os conectores <b>"porém"</b> e <b>"contudo"</b> expressam <b>causa</b>, introduzindo a razão de um fato anterior.',a:false,e:'Porém/contudo/todavia = ADVERSATIVO (oposição). Causa = porque/pois/já que/uma vez que.'},
{n:10,t:'Português – Colocação',q:'Em início de frase, a <b>ênclise</b> é a colocação pronominal recomendada na norma culta escrita brasileira.',a:true,e:'Não se inicia frase com pronome oblíquo átono. "Disse-me" ✅. "Me disse" ❌ (na norma culta escrita).'},
{n:11,t:'Português – Tipologia',q:'O texto <b>dissertativo-argumentativo</b> tem como objetivo principal <b>narrar fatos</b> em sequência cronológica.',a:false,e:'Dissertativo-argumentativo = defesa de tese. Narrar fatos em sequência = texto NARRATIVO.'},
{n:12,t:'Português – Reescrita',q:'Substituir <b>"conquanto"</b> por <b>"porque"</b> mantém a relação de sentido original da oração.',a:false,e:'Conquanto = embora (concessão). Porque = causa. Relações completamente diferentes.'},
{n:13,t:'Português – Ortografia',q:'Toda palavra <b>proparoxítona</b> é acentuada graficamente na língua portuguesa.',a:true,e:'Regra sem exceção: todas proparoxítonas levam acento. Ex: lâmpada, médico, matemática.'},
{n:14,t:'Português – Oração relativa',q:'Na frase "O livro <b>que</b> li era bom", o "que" é pronome relativo com função de <b>objeto direto</b> de "li".',a:true,e:'"Que" retoma "livro" e funciona como OD: "li o livro (=que)".'},
{n:15,t:'Português – Adjetiva',q:'A oração adjetiva <b>restritiva</b> vem isolada por vírgulas e acrescenta informação acessória.',a:false,e:'Restritiva = SEM vírgulas (delimita). Explicativa = COM vírgulas (acessória). A vírgula muda tudo.'},

// ── LÍNGUA INGLESA (16-30) ──
{n:16,t:'Inglês – False Friends',q:'A palavra inglesa <b>"eventually"</b> significa "eventualmente" em português.',a:false,e:'False friend! "Eventually" = finalmente/por fim. "Eventualmente" = occasionally.'},
{n:17,t:'Inglês – Verb Tenses',q:'No <b>Present Perfect</b> (have/has + PP), a ação passada tem conexão com o presente. Combina com "since" e "for".',a:true,e:'Present Perfect: ação passada com relevância presente. Since (ponto), for (período).'},
{n:18,t:'Inglês – Modals',q:'<b>"Must not"</b> (proibição) e <b>"don\'t have to"</b> (ausência de obrigação) possuem o mesmo significado.',a:false,e:'Must not = PROIBIDO. Don\'t have to = não precisa. Significados opostos.'},
{n:19,t:'Inglês – Connectors',q:'O conector <b>"however"</b> expressa <b>contraste</b>, equivalendo a "nevertheless" ou "nonetheless".',a:true,e:'However/nevertheless/nonetheless = porém/contudo. Todos expressam oposição.'},
{n:20,t:'Inglês – Passive Voice',q:'Na voz passiva em inglês, a estrutura é <b>to be + past participle</b>: "The law <b>was approved</b>".',a:true,e:'Passive: subject + to be + PP (+ by agent). Foco no objeto da ação.'},
{n:21,t:'Inglês – False Friends',q:'A palavra <b>"pretend"</b> em inglês significa "pretender" (ter a intenção) em português.',a:false,e:'False friend! "Pretend" = fingir. "Pretender" = intend/plan.'},
{n:22,t:'Inglês – Conditionals',q:'"If I <b>had studied</b>, I <b>would have passed</b>" é um <b>3rd conditional</b> (hipótese irreal no passado).',a:true,e:'3rd conditional: If + past perfect, would have + PP. Situação irreal no passado.'},
{n:23,t:'Inglês – Despite/Although',q:'<b>"Despite"</b> pode ser seguido diretamente de oração com sujeito+verbo: "despite it rained".',a:false,e:'Despite/in spite of + noun/gerund. "Despite the rain" ✅. Oração = use "although".'},
{n:24,t:'Inglês – Vocabulary',q:'<b>"Law enforcement"</b> refere-se à aplicação da lei e designa forças policiais/de segurança.',a:true,e:'Law enforcement = forças de segurança. Law enforcement officer = agente policial.'},
{n:25,t:'Inglês – Reference',q:'Em "The officers completed <b>their</b> training", "their" refere-se a "officers".',a:true,e:'"Their" = pronome possessivo referente ao sujeito plural "officers".'},
{n:26,t:'Inglês – Reading',q:'<b>Skimming</b> é a leitura detalhada, palavra por palavra, para compreensão total do texto.',a:false,e:'Skimming = leitura rápida/ideia geral. Scanning = busca específica. Detalhada = intensive reading.'},
{n:27,t:'Inglês – Word Formation',q:'O sufixo <b>"-ment"</b> transforma verbo em substantivo: develop → development, govern → government.',a:true,e:'-ment: verbo → substantivo. Outros: -tion, -ness, -ity.'},
{n:28,t:'Inglês – Modals',q:'O modal <b>"should"</b> expressa obrigação forte, equivalendo a "must".',a:false,e:'Should = conselho/recomendação. Must = obrigação forte. Should é mais leve.'},
{n:29,t:'Inglês – Comparatives',q:'Para adjetivos longos, o comparativo usa <b>"more"</b> + adj: "more important than".',a:true,e:'Longos (2+ sílabas): more + adj. Curtos: adj + -er. Irregular: good→better, bad→worse.'},
{n:30,t:'Inglês – False Friends',q:'<b>"Sensible"</b> em inglês significa "sensato/prudente", e não "sensível".',a:true,e:'Sensible = sensato. Sensitive = sensível. False friend clássico CEBRASPE.'},

// ── RACIOCÍNIO LÓGICO E ESTATÍSTICA (31-45) ──
{n:31,t:'RLM – Condicional',q:'A proposição condicional P→Q é falsa <b>apenas</b> quando P é verdadeira e Q é falsa.',a:true,e:'Macete "Vera Fischer": V→F = FALSO. Demais combinações = V.'},
{n:32,t:'RLM – Negação',q:'A negação de "Se chove, então molha" (P→Q) é "Se não chove, então não molha" (~P→~Q).',a:false,e:'~P→~Q é a INVERSA! Negação de P→Q = P ∧ ~Q (MANE: mantém a 1ª E nega a 2ª).'},
{n:33,t:'RLM – De Morgan',q:'Pela Lei de De Morgan, ~(P ∧ Q) ≡ (~P ∨ ~Q).',a:true,e:'De Morgan: nega ambas e troca operador. ~(P∧Q) = ~P∨~Q e ~(P∨Q) = ~P∧~Q.'},
{n:34,t:'RLM – Equivalência',q:'A contrapositiva de P→Q é Q→P (inversão simples das proposições).',a:false,e:'Contrapositiva = ~Q→~P (inverte E nega). Q→P é a RECÍPROCA (não equivale).'},
{n:35,t:'RLM – Tabela-verdade',q:'Uma tabela-verdade com 3 proposições simples distintas possui <b>8 linhas</b>.',a:true,e:'Linhas = 2ⁿ. Com n=3: 2³ = 8 linhas.'},
{n:36,t:'RLM – Modus Tollens',q:'Se P→Q e ~Q, podemos concluir ~P (Modus Tollens).',a:true,e:'Modus Tollens: nega consequente → nega antecedente. P→Q, ~Q ∴ ~P. Válido.'},
{n:37,t:'RLM – Falácia',q:'O argumento "Se chove, molha. Molhou. Logo, choveu." é <b>válido</b>.',a:false,e:'Falácia da afirmação do consequente! P→Q, Q ∴ P é INVÁLIDO. Pode ter molhado por outra causa.'},
{n:38,t:'RLM – Contagem',q:'Na <b>combinação</b> C(n,p), a ordem dos elementos importa.',a:false,e:'Combinação: ordem NÃO importa (AB=BA). Ordem importa = arranjo/permutação.'},
{n:39,t:'RLM – Probabilidade',q:'P(pelo menos um) pode ser calculada como 1 − P(nenhum).',a:true,e:'P(pelo menos 1) = 1 − P(nenhum). Atalho fundamental.'},
{n:40,t:'RLM – Conjuntos',q:'|A∪B| = |A| + |B| − |A∩B| (princípio da inclusão-exclusão).',a:true,e:'Subtrai interseção para não contar duas vezes.'},
{n:41,t:'RLM – Equivalência',q:'P→Q é logicamente equivalente a ~P ∨ Q.',a:true,e:'P→Q ≡ ~P∨Q. Equivalência fundamental da condicional.'},
{n:42,t:'RLM – Estatística',q:'A <b>mediana</b> é mais afetada por outliers do que a média.',a:false,e:'CONTRÁRIO! A MÉDIA é puxada por outliers. Mediana é robusta a valores extremos.'},
{n:43,t:'RLM – Estatística',q:'A variância amostral divide por <b>(n−1)</b>, enquanto a populacional divide por n.',a:true,e:'Amostral: ÷(n−1) — correção de Bessel. Populacional: ÷n.'},
{n:44,t:'RLM – Estatística',q:'Em distribuição com assimetria positiva (cauda direita), a média é maior que a mediana.',a:true,e:'Assimetria positiva: Média > Mediana > Moda.'},
{n:45,t:'RLM – Quantificadores',q:'A negação de "Todo policial é treinado" é "Nenhum policial é treinado".',a:false,e:'Negação de "Todo A é B" = "Algum A NÃO é B". "Nenhum" nega "Algum...é".'},

// ── DIREITO CONSTITUCIONAL (46-60) ──
{n:46,t:'Constitucional – Fundamentos',q:'Os fundamentos da República (art. 1º CF) são: soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa, pluralismo político (SOCIDIVAPLU).',a:true,e:'Art. 1º CF: SO-CI-DI-VA-PLU. Macete dos 5 fundamentos.'},
{n:47,t:'Constitucional – Art. 5º',q:'Os direitos fundamentais do art. 5º aplicam-se <b>apenas</b> aos cidadãos brasileiros, excluindo estrangeiros.',a:false,e:'Art. 5º: brasileiros E estrangeiros residentes. STF estende a estrangeiros em trânsito.'},
{n:48,t:'Constitucional – Aplicação',q:'As normas definidoras de direitos e garantias fundamentais têm <b>aplicação imediata</b> (art. 5º, §1º CF).',a:true,e:'Art. 5º, §1º CF. Cobrado em TRF6/2025, TRT10/2025 pelo CEBRASPE.'},
{n:49,t:'Constitucional – CPI',q:'A CPI pode determinar quebra de sigilo bancário e fiscal, mas <b>não</b> pode determinar interceptação telefônica (reserva de jurisdição).',a:true,e:'CPI pode: sigilo bancário/fiscal/dados. NÃO pode: interceptação, prisão (salvo flagrante), busca domiciliar.'},
{n:50,t:'Constitucional – Imunidade',q:'A imunidade material dos parlamentares (opiniões, palavras e votos) é <b>absoluta</b> no exercício do mandato.',a:true,e:'Art. 53 CF: inviolabilidade material absoluta. Exclui responsabilidade penal e civil.'},
{n:51,t:'Constitucional – Competência',q:'A competência <b>privativa</b> da União (art. 22) pode ser delegada por <b>lei complementar</b>.',a:true,e:'Privativa = delegável por LC. Exclusiva (art. 21) = indelegável.'},
{n:52,t:'Constitucional – MP',q:'Medida Provisória pode versar sobre direito penal e processual penal.',a:false,e:'Art. 62, §1º CF: MP NÃO pode versar sobre direito penal/processual penal/civil.'},
{n:53,t:'Constitucional – RICD',q:'A Mesa da Câmara é composta por 7 membros (Presidente, 2 Vice-Presidentes, 4 Secretários), mandato de 2 anos, vedada recondução na mesma legislatura.',a:true,e:'RICD: Mesa = 7 membros. Mandato 2 anos, vedada recondução para mesmo cargo.'},
{n:54,t:'Constitucional – Adm. Pública',q:'O princípio da <b>eficiência</b> foi incluído no art. 37 CF pela EC 19/1998 (Reforma Administrativa).',a:true,e:'LIMPE: eficiência foi o último, EC 19/1998 (Reforma Gerencial).'},
{n:55,t:'Constitucional – Remédios',q:'O <b>habeas data</b> é o remédio para garantir o direito de locomoção.',a:false,e:'Habeas data = dados pessoais. Locomoção = habeas CORPUS.'},
{n:56,t:'Constitucional – Segurança',q:'O art. 144 CF inclui as Polícias Penais como órgãos de segurança pública (EC 104/2019).',a:true,e:'EC 104/2019 incluiu polícias penais (federal, estadual, distrital) no art. 144.'},
{n:57,t:'Constitucional – Nacionalidade',q:'São privativos de brasileiros natos os cargos de Presidente, Vice, Presidente da Câmara, do Senado e Ministro do STF.',a:true,e:'Art. 12, §3º CF: cargos privativos de nato.'},
{n:58,t:'Constitucional – Defesa',q:'O estado de defesa pode ser decretado pelo Presidente <b>sem</b> autorização prévia do CN.',a:true,e:'Defesa: decreta PRIMEIRO, CN aprova DEPOIS. Sítio: CN autoriza ANTES.'},
{n:59,t:'Constitucional – Servidor',q:'Servidor público estável adquire estabilidade após <b>3 anos</b> de exercício + avaliação especial.',a:true,e:'Art. 41 CF: 3 anos + avaliação especial de desempenho.'},
{n:60,t:'Constitucional – Tratados DH',q:'Tratados de DH aprovados com rito de EC (3/5, 2 turnos, 2 casas) têm status <b>supralegal</b>.',a:false,e:'Rito de EC = EMENDA CONSTITUCIONAL. Rito ordinário = supralegal. RE 466.343/STF.'},

// ── DIREITO ADMINISTRATIVO (61-75) ──
{n:61,t:'Administrativo – LIMPE',q:'Os princípios expressos da Administração (art. 37 CF) são Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.',a:true,e:'LIMPE: art. 37, caput, CF. Memorize os 5 princípios expressos.'},
{n:62,t:'Administrativo – Discricionário',q:'No ato discricionário, o administrador possui liberdade sobre <b>todos</b> os elementos, incluindo finalidade.',a:false,e:'Competência, finalidade e forma = VINCULADOS. Discricionariedade: apenas motivo e objeto.'},
{n:63,t:'Administrativo – Autotutela',q:'A Administração pode anular seus atos quando eivados de ilegalidade, sem provocação judicial (autotutela).',a:true,e:'Súmula 473/STF: anular=ilegalidade. Revogar=conveniência.'},
{n:64,t:'Administrativo – Improbidade',q:'Após Lei 14.230/2021, todos os atos de improbidade exigem <b>dolo</b>. Não há mais modalidade culposa.',a:true,e:'Reforma 2021: fim da improbidade culposa. Só dolo.'},
{n:65,t:'Administrativo – Concurso',q:'Prazo de validade do concurso: até <b>2 anos</b>, prorrogável uma vez por igual período.',a:true,e:'Art. 37, III, CF: 2+2 anos máximo.'},
{n:66,t:'Administrativo – Poder de Polícia',q:'O poder de polícia pode ser integralmente delegado a pessoas jurídicas de direito privado.',a:false,e:'Poder de polícia: atos de consentimento e fiscalização podem ser delegados (RE 633782/STF), mas o ciclo completo não.'},
{n:67,t:'Administrativo – Responsabilidade',q:'A responsabilidade civil do Estado é <b>objetiva</b> (teoria do risco administrativo), conforme art. 37, §6º CF.',a:true,e:'Estado = objetiva. Agente = subjetiva (ação regressiva se dolo/culpa).'},
{n:68,t:'Administrativo – Organização',q:'Autarquias são <b>criadas</b> por lei específica; EP e SEM têm criação <b>autorizada</b> por lei.',a:true,e:'Art. 37, XIX CF. Autarquia = criada. EP/SEM = autorizada + registro.'},
{n:69,t:'Administrativo – Licitação',q:'Na Lei 14.133/2021, o <b>termo de referência</b> define objeto, especificações e condições da contratação.',a:true,e:'Art. 6º, XXIII, Lei 14.133: termo de referência para bens e serviços.'},
{n:70,t:'Administrativo – Perda do cargo',q:'Servidor estável pode perder o cargo por sentença judicial, PAD ou avaliação periódica de desempenho.',a:true,e:'Art. 41, §1º CF: 3 hipóteses + excesso de despesa (art. 169).'},
{n:71,t:'Administrativo – Revogação',q:'A revogação de ato administrativo produz efeitos <b>ex tunc</b> (retroativos).',a:false,e:'Revogação = EX NUNC (prospectivo). Anulação = EX TUNC (retroage).'},
{n:72,t:'Administrativo – PAD',q:'O PAD é conduzido por comissão de <b>3 servidores estáveis</b>.',a:true,e:'Lei 8.112, art. 149: comissão de 3 servidores estáveis.'},
{n:73,t:'Administrativo – Hierarquia',q:'O poder hierárquico permite avocação, delegação e fiscalização dos subordinados.',a:true,e:'Poder hierárquico: relação interna de subordinação.'},
{n:74,t:'Administrativo – TCU',q:'O Tribunal de Contas da União é órgão do Poder Judiciário.',a:false,e:'TCU = órgão AUXILIAR do Poder LEGISLATIVO no controle externo.'},
{n:75,t:'Administrativo – LAI',q:'A LAI (Lei 12.527/2011) estabelece 3 graus de sigilo: reservado (5 anos), secreto (15 anos) e ultrassecreto (25 anos).',a:true,e:'5-15-25 anos. Macete: cresce de 10 em 10.'},

// ── INFORMÁTICA E DADOS (76-90) ──
{n:76,t:'Informática – CID',q:'A tríade da segurança da informação: <b>Confidencialidade, Integridade e Disponibilidade</b>.',a:true,e:'CID: confidencialidade (acesso restrito), integridade (sem alteração), disponibilidade (sempre acessível).'},
{n:77,t:'Informática – Malware',q:'Um <b>worm</b> se propaga automaticamente, <b>sem</b> necessidade de programa hospedeiro.',a:true,e:'Worm = autopropagação sem hospedeiro. Vírus = precisa de hospedeiro + ação do usuário.'},
{n:78,t:'Informática – Ransomware',q:'<b>Ransomware</b> criptografa arquivos da vítima e exige pagamento de resgate.',a:true,e:'Ransom = resgate. Criptografa e cobra. WannaCry é exemplo clássico.'},
{n:79,t:'Informática – Phishing',q:'Phishing por <b>voz</b> chama-se <b>vishing</b>; por SMS chama-se <b>smishing</b>.',a:true,e:'Phishing (e-mail), vishing (voice), smishing (SMS).'},
{n:80,t:'Informática – Criptografia',q:'Na criptografia <b>simétrica</b>, utilizam-se duas chaves diferentes (pública e privada).',a:false,e:'Simétrica = UMA chave. Assimétrica = duas (pública/privada).'},
{n:81,t:'Informática – Assinatura',q:'A assinatura digital garante autenticidade, integridade e não repúdio, usando a chave <b>privada</b> para assinar.',a:true,e:'Assinar = chave privada. Verificar = chave pública. Garante AIN (autenticidade, integridade, não repúdio).'},
{n:82,t:'Informática – Cloud',q:'No modelo <b>IaaS</b>, o provedor oferece infraestrutura e o cliente gerencia SO e aplicações.',a:true,e:'IaaS: infra. PaaS: plataforma. SaaS: software pronto.'},
{n:83,t:'Informática – Redes',q:'O <b>TCP</b> é orientado a conexão e garante entrega, enquanto <b>UDP</b> é mais rápido mas sem garantia.',a:true,e:'TCP = confiável. UDP = rápido sem garantia.'},
{n:84,t:'Informática – BD',q:'A chave primária (PK) identifica unicamente cada registro e não admite valores nulos.',a:true,e:'PK: única + not null. FK referencia PK de outra tabela.'},
{n:85,t:'Informática – Forense',q:'Na forense, a <b>ordem de volatilidade</b> determina coletar primeiro dados mais voláteis (ex: RAM).',a:true,e:'Ordem: registros → RAM → disco. RAM é muito mais volátil que disco.'},
{n:86,t:'Informática – Cadeia Custódia',q:'A cópia forense deve ser verificada por <b>hash</b> (MD5/SHA) para garantir integridade.',a:true,e:'Imagem bit-a-bit + hash garante que evidência não foi alterada.'},
{n:87,t:'Informática – Big Data',q:'Os 5 Vs do Big Data: Volume, Velocidade, Variedade, Veracidade e Valor.',a:true,e:'5 Vs: memorize todos. Veracidade e Valor são os menos lembrados.'},
{n:88,t:'Informática – IA',q:'IA Generativa é subcampo do Machine Learning capaz de criar conteúdo novo a partir de padrões.',a:true,e:'Hierarquia: IA → ML → Deep Learning → IA Generativa.'},
{n:89,t:'Informática – Windows',q:'No Windows, <b>Ctrl+Shift+Esc</b> abre diretamente o Gerenciador de Tarefas.',a:true,e:'Ctrl+Shift+Esc = direto. Ctrl+Alt+Del = tela de opções.'},
{n:90,t:'Informática – LGPD',q:'Na LGPD, o <b>controlador</b> decide sobre tratamento; o <b>operador</b> executa em nome do controlador.',a:true,e:'Controlador = decide. Operador = executa. DPO = canal com titulares e ANPD.'}
];

// ──────────────────────────────────────────────────────
// CONHECIMENTOS ESPECÍFICOS (90 itens)
// Penal/Processual(30) + Criminologia/Criminalística(20) + Dir.Humanos(20) + Inteligência(20)
// ──────────────────────────────────────────────────────
const CE = [
// ── DIREITO PENAL E PROCESSUAL PENAL (1-30) ──
{n:1,t:'Penal – Anterioridade',q:'O princípio da anterioridade impede retroatividade da lei penal, <b>salvo</b> quando a lei posterior for mais benéfica ao réu.',a:true,e:'Art. 5º, XL CF e art. 2º CP: retroatividade benéfica. Princípio fundamental.'},
{n:2,t:'Penal – Insignificância',q:'O princípio da insignificância (bagatela) é causa de exclusão da <b>tipicidade material</b>.',a:true,e:'Exclui tipicidade material, não formal. Requisitos: mínima ofensividade, nenhuma periculosidade social, reduzido grau de reprovabilidade, inexpressividade da lesão.'},
{n:3,t:'Penal – Tempo do Crime',q:'O CP adota a <b>teoria da atividade</b>: crime praticado no momento da ação ou omissão.',a:true,e:'Art. 4º CP: atividade (tempo). Art. 6º CP: ubiquidade (lugar). Mnemônico: LUTA.'},
{n:4,t:'Penal – Abolitio Criminis',q:'A abolitio criminis faz cessar todos os efeitos penais <b>e civis</b> da condenação.',a:false,e:'Cessa efeitos PENAIS, mas NÃO os cíveis. Obrigação de reparar o dano permanece.'},
{n:5,t:'Penal – Legítima Defesa',q:'A legítima defesa é causa excludente de <b>culpabilidade</b>.',a:false,e:'Legítima defesa exclui ILICITUDE (antijuridicidade). Culpabilidade: inimputabilidade, coação moral irresistível, etc.'},
{n:6,t:'Penal – Excludentes',q:'São excludentes de ilicitude: estado de necessidade, legítima defesa, estrito cumprimento de dever legal e exercício regular de direito.',a:true,e:'Art. 23 CP: as 4 excludentes de ilicitude. LEEE.'},
{n:7,t:'Penal – Embriaguez',q:'A embriaguez <b>voluntária</b> exclui a imputabilidade penal.',a:false,e:'Voluntária/culposa NÃO exclui (actio libera in causa). Só completa + fortuito/força maior.'},
{n:8,t:'Penal – Tentativa',q:'Na tentativa, a pena é reduzida de <b>1/3 a 2/3</b>, conforme proximidade da consumação.',a:true,e:'Art. 14, parágrafo único CP. Quanto mais perto da consumação, menor a redução.'},
{n:9,t:'Penal – Teoria Monista',q:'Na teoria monista, adotada pelo CP, todos que concorrem para o crime respondem pelo mesmo tipo penal.',a:true,e:'Art. 29 CP: coautores e partícipes respondem pelo mesmo crime.'},
{n:10,t:'Penal – Comunicabilidade',q:'Circunstâncias de caráter pessoal se comunicam entre coautores em <b>todos os casos</b>.',a:false,e:'Art. 30 CP: pessoais NÃO se comunicam, SALVO quando elementares do crime.'},
{n:11,t:'Penal – Peculato',q:'O peculato consiste na apropriação ou desvio de bem público por funcionário que tem posse em razão do cargo.',a:true,e:'Art. 312 CP: peculato-apropriação e peculato-desvio. Posse legítima + apropriação/desvio.'},
{n:12,t:'Penal – Concussão',q:'No crime de concussão (art. 316 CP), o funcionário público <b>solicita</b> vantagem indevida.',a:false,e:'Concussão = EXIGIR. Corrupção passiva = SOLICITAR/RECEBER. Exigir ≠ solicitar!'},
{n:13,t:'Penal – Arrependimento',q:'O arrependimento posterior (art. 16 CP) exige reparação até o <b>recebimento da denúncia</b>, em crimes sem violência.',a:true,e:'Art. 16: sem violência/grave ameaça + reparação antes da denúncia. Reduz 1/3 a 2/3.'},
{n:14,t:'Penal – Prescrição',q:'Antes do trânsito em julgado, a prescrição calcula-se pela pena <b>máxima</b> cominada.',a:true,e:'Antes = pena máxima abstrata. Após = pena concretamente aplicada.'},
{n:15,t:'Penal – Abuso Autoridade',q:'Crimes de abuso de autoridade (Lei 13.869/2019) são de ação penal pública <b>incondicionada</b>.',a:true,e:'Art. 3º Lei 13.869: AP pública incondicionada. Admite subsidiária da pública.'},
{n:16,t:'Processual – Flagrante',q:'O flagrante delito pode ser realizado por qualquer pessoa do povo, sem mandado judicial.',a:true,e:'Art. 301 CPP: qualquer do povo PODE; autoridade policial DEVE.'},
{n:17,t:'Processual – IP',q:'O inquérito policial é peça <b>indispensável</b> para o oferecimento da denúncia.',a:false,e:'IP é DISPENSÁVEL. MP pode denunciar com base em outras fontes.'},
{n:18,t:'Processual – Prisão Temporária',q:'Prisão temporária: <b>5+5</b> dias (regra) e <b>30+30</b> dias em crimes hediondos.',a:true,e:'Lei 7.960/89: 5+5. Hediondos (Lei 8.072/90): 30+30.'},
{n:19,t:'Processual – Preventiva',q:'O juiz pode decretar prisão preventiva de <b>ofício</b> durante a investigação policial.',a:false,e:'Pacote Anticrime: juiz NÃO decreta de ofício em nenhuma fase. Requer provocação.'},
{n:20,t:'Processual – Prova Ilícita',q:'A prova ilícita contamina as derivadas pela teoria dos <b>frutos da árvore envenenada</b>.',a:true,e:'Art. 5º, LVI CF e art. 157 CPP. Exceções: fonte independente, descoberta inevitável.'},
{n:21,t:'Processual – Corpo Delito',q:'O exame de corpo de delito é indispensável quando há vestígios e não pode ser suprido pela confissão.',a:true,e:'Art. 158 CPP: confissão NUNCA supre. Pode ser suprido por testemunhal quando vestígios desaparecem.'},
{n:22,t:'Processual – Peritos',q:'Na falta de perito oficial, o exame pode ser feito por <b>uma única</b> pessoa idônea com diploma superior.',a:false,e:'Art. 159, §1º CPP: DUAS pessoas idôneas com diploma superior.'},
{n:23,t:'Processual – Júri',q:'O Tribunal do Júri julga crimes <b>dolosos contra a vida</b>, com sigilo das votações.',a:true,e:'Art. 5º, XXXVIII CF. Garantias: plenitude de defesa, sigilo, soberania dos veredictos.'},
{n:24,t:'Penal – Maria da Penha',q:'Lesão corporal leve no âmbito da Lei Maria da Penha é de ação penal pública <b>condicionada</b> à representação.',a:false,e:'Súmula 542/STJ e ADI 4424/STF: INCONDICIONADA.'},
{n:25,t:'Penal – Drogas',q:'O tráfico de drogas é equiparado a hediondo, sendo inafiançável e insuscetível de graça ou anistia.',a:true,e:'Art. 5º, XLIII CF: tráfico = equiparado a hediondo.'},
{n:26,t:'Penal – ECA',q:'Menores de 18 anos são penalmente inimputáveis, sujeitando-se a medidas socioeducativas.',a:true,e:'Art. 228 CF e art. 104 ECA: critério biológico.'},
{n:27,t:'Processual – Ação Penal',q:'A ação penal pública é de titularidade do MP e se inicia por <b>denúncia</b>.',a:true,e:'MP = denúncia (pública). Ofendido = queixa-crime (privada).'},
{n:28,t:'Penal – Hediondos',q:'Progressão de regime em hediondos: <b>40%</b> para réu primário.',a:true,e:'Pacote Anticrime: primário=40%, reincidente genérico=50%, específico=60%.'},
{n:29,t:'Processual – Foro',q:'Deputados federais têm foro por prerrogativa de função no <b>STF</b> para crimes no exercício e em razão do cargo.',a:true,e:'Art. 53, §1º CF. AP 937/STF: apenas crimes no exercício E em razão do cargo.'},
{n:30,t:'Penal – LEP',q:'A remição pelo trabalho na LEP: a cada <b>3 dias</b> trabalhados, remite-se 1 dia de pena.',a:true,e:'Art. 126 LEP: trabalho 3:1. Estudo 12h:1 dia.'},

// ── CRIMINOLOGIA E CRIMINALÍSTICA (31-50) ──
{n:31,t:'Criminalística – Cadeia Custódia',q:'O início da cadeia de custódia dá-se com a <b>preservação do local de crime</b> ou detecção de vestígio.',a:true,e:'Art. 158-A CPP: início = preservação do local ou procedimento com vestígio.'},
{n:32,t:'Criminalística – Corpo Delito',q:'A prova testemunhal é inidônea para suprir o exame de corpo de delito em qualquer hipótese.',a:false,e:'Art. 167 CPP: testemunhal PODE suprir quando vestígios desaparecerem. Não é inidônea.'},
{n:33,t:'Criminalística – Locard',q:'O princípio de <b>Locard</b> afirma que todo contato deixa vestígios (princípio da troca).',a:true,e:'Edmond Locard: "todo contato deixa uma marca". Princípio fundamental da criminalística.'},
{n:34,t:'Criminalística – 10 Etapas',q:'A cadeia de custódia possui <b>10 etapas</b>: reconhecimento, isolamento, fixação, coleta, acondicionamento, transporte, recebimento, processamento, armazenamento e descarte.',a:true,e:'Art. 158-B a 158-F CPP. As 10 etapas devem ser documentadas.'},
{n:35,t:'Criminalística – Necropsia',q:'A necropsia deve ser realizada pelo menos <b>6 horas</b> após o óbito, salvo se os peritos julgarem desnecessária a espera.',a:true,e:'Art. 162 CPP: 6 horas após óbito, exceto se peritos entenderem que a espera é desnecessária.'},
{n:36,t:'Criminalística – Perito ad hoc',q:'Na falta de perito oficial, o exame pode ser feito por <b>duas pessoas idôneas</b> com curso superior, que prestarão compromisso.',a:true,e:'Art. 159, §1º CPP: duas pessoas idôneas, portadoras de diploma de nível superior, preferencialmente na área.'},
{n:37,t:'Criminalística – Vestígios',q:'Vestígios <b>latentes</b> são aqueles visíveis a olho nu, sem necessidade de técnica especial.',a:false,e:'Latentes = NÃO visíveis, necessitam técnica (ex: impressão digital latente). Visíveis = patentes.'},
{n:38,t:'Criminalística – Forense DNA',q:'A técnica de <b>PCR</b> é utilizada na genética forense para amplificar pequenas quantidades de DNA.',a:true,e:'PCR (Polymerase Chain Reaction): amplifica DNA para análise. Essencial na identificação humana.'},
{n:39,t:'Criminalística – Balística',q:'Na balística forense, a <b>microcomparação</b> permite identificar se um projétil foi disparado por arma específica.',a:true,e:'Estrias e microestrias são únicas para cada arma. Microscópio comparador balístico.'},
{n:40,t:'Criminalística – Documentoscopia',q:'A <b>grafoscopia</b> estuda a autenticidade de escritas e assinaturas manuscritas.',a:true,e:'Grafoscopia = análise de escrita manual. Ramo da documentoscopia.'},
{n:41,t:'Criminologia – Escola Clássica',q:'A Escola Clássica da Criminologia foca no <b>criminoso</b> e nas causas biológicas do crime.',a:false,e:'Clássica foca no CRIME (fato), não no criminoso. Causas biológicas = Escola POSITIVA (Lombroso).'},
{n:42,t:'Criminologia – Escola Positiva',q:'Cesare <b>Lombroso</b>, da Escola Positiva, propôs o conceito de "criminoso nato" com base em características biológicas.',a:true,e:'Lombroso = criminoso nato (atavismo). Ferri = fatores sociais. Garofalo = temibilidade.'},
{n:43,t:'Criminologia – Labelling',q:'A teoria do <b>labelling approach</b> (etiquetamento) sustenta que o crime é uma construção social e o sistema penal é seletivo.',a:true,e:'Labelling/interacionismo: o desvio é definido pela reação social. Foco no controle social, não no criminoso.'},
{n:44,t:'Criminologia – Prevenção',q:'A prevenção <b>primária</b> atua sobre as causas estruturais do crime (educação, saúde, emprego).',a:true,e:'Primária=causas (políticas sociais). Secundária=grupos de risco (policiamento). Terciária=ressocialização (preso).'},
{n:45,t:'Criminologia – Vitimologia',q:'<b>Mendelsohn</b> classificou as vítimas segundo seu grau de participação no crime, de totalmente inocente a totalmente culpada.',a:true,e:'Classificação de Mendelsohn: 6 graus de vítima, do inocente ao provocador.'},
{n:46,t:'Criminologia – Cifra Negra',q:'A <b>cifra negra</b> refere-se ao percentual de crimes que <b>não</b> chegam ao conhecimento das autoridades.',a:true,e:'Cifra negra = criminalidade oculta. Cifra dourada = crimes do colarinho branco não apurados.'},
{n:47,t:'Criminologia – Controle',q:'O controle social <b>formal</b> é exercido por instituições como polícia, Judiciário e sistema penitenciário.',a:true,e:'Formal: polícia, MP, Judiciário, prisão. Informal: família, escola, religião, mídia.'},
{n:48,t:'Criminologia – Janelas Quebradas',q:'A teoria das <b>janelas quebradas</b> sugere que a desordem urbana estimula o aumento da criminalidade.',a:true,e:'Wilson e Kelling (1982): desordem → sensação de impunidade → mais crimes.'},
{n:49,t:'Criminologia – Justiça Restaurativa',q:'A justiça <b>restaurativa</b> busca a reparação do dano e a reconciliação entre vítima, ofensor e comunidade.',a:true,e:'Restaurativa: foco na vítima e reparação. Diferente da retributiva (foco na punição).'},
{n:50,t:'Criminologia – Funções da Pena',q:'A teoria <b>absolutista</b> (retributiva) da pena justifica a punição como retribuição proporcional ao mal causado.',a:true,e:'Absoluta/retributiva: pena como castigo merecido. Relativa/preventiva: prevenção geral/especial.'},

// ── DIREITOS HUMANOS (51-70) ──
{n:51,t:'DH – Gerações',q:'Os DH de <b>1ª geração</b> são os direitos de liberdade (civis e políticos), surgidos com o liberalismo.',a:true,e:'1ª=liberdade (civis/políticos). 2ª=igualdade (sociais/econômicos). 3ª=fraternidade (solidariedade).'},
{n:52,t:'DH – DUDH',q:'A DUDH de 1948 tem natureza de <b>tratado internacional vinculante</b> para todos os Estados membros da ONU.',a:false,e:'DUDH = resolução da AG/ONU (recomendação). Não é tratado vinculante. Tem força moral/costumeira.'},
{n:53,t:'DH – DUDH',q:'A DUDH rechaça todas as formas de escravidão <b>e</b> o tráfico de pessoas escravizadas (art. 4º).',a:true,e:'Art. 4º DUDH: ninguém será mantido em escravidão ou servidão; tráfico de escravos proibido em todas as formas.'},
{n:54,t:'DH – Hierarquia Tratados',q:'Tratados de DH aprovados com rito de EC têm status constitucional; os demais têm status <b>supralegal</b>.',a:true,e:'Art. 5º, §3º CF: rito EC = constitucional. Rito ordinário = supralegal (RE 466.343/STF).'},
{n:55,t:'DH – CADH',q:'A CADH (Pacto de São José) foi ratificada pelo Brasil em <b>1992</b> e protege direitos civis e políticos.',a:true,e:'CADH = 1969, ratificada pelo Brasil em 1992. Foco em direitos civis/políticos.'},
{n:56,t:'DH – Comissão vs Corte',q:'A <b>Comissão Interamericana</b> (CIDH) emite sentenças vinculantes contra os Estados.',a:false,e:'Comissão = recomendações (não vinculantes). Corte = sentenças vinculantes. Só a Corte julga.'},
{n:57,t:'DH – CADH Suspensão',q:'O art. 27 da CADH permite a suspensão de garantias em caso de guerra ou perigo público, mas há direitos <b>inderrogáveis</b>.',a:true,e:'Inderrogáveis: vida, integridade, proibição escravidão, legalidade penal, nome, nacionalidade, direitos políticos, proteção judicial.'},
{n:58,t:'DH – Princípio Pro Persona',q:'O princípio <b>pro persona</b> determina a aplicação da norma <b>mais favorável</b> ao ser humano.',a:true,e:'Pro persona/pro homine: na dúvida, aplica-se a norma mais protetiva ao indivíduo.'},
{n:59,t:'DH – Universalidade',q:'O princípio da <b>universalidade</b> dos DH significa que são direitos de TODOS, independentemente de condição.',a:true,e:'Declaração de Viena (1993): DH são universais, indivisíveis, interdependentes e inter-relacionados.'},
{n:60,t:'DH – Corte IDH',q:'A Corte Interamericana pode processar <b>indivíduos</b> diretamente por violações de direitos humanos.',a:false,e:'Corte julga ESTADOS, não indivíduos. Só Comissão e Estados partes podem acionar a Corte.'},
{n:61,t:'DH – IDC',q:'O Incidente de Deslocamento de Competência (IDC) permite transferir para a Justiça Federal inquéritos sobre grave violação de DH.',a:true,e:'Art. 109, V-A e §5º CF (EC 45/2004). PGR requer ao STJ. Justiça Federal assume.'},
{n:62,t:'DH – CF/88',q:'A <b>dignidade da pessoa humana</b> é fundamento da República (art. 1º, III CF) e base de todo o sistema de DH na CF.',a:true,e:'Dignidade = fundamento (não objetivo). Pilar axiológico da CF/88.'},
{n:63,t:'DH – Pena de Morte',q:'A CADH proíbe absolutamente a pena de morte em qualquer circunstância.',a:false,e:'CADH permite pena de morte já existente, mas proíbe sua extensão a novos crimes e para crimes políticos. Países que aboliram não podem restabelecer.'},
{n:64,t:'DH – Agenda 2030',q:'A Agenda 2030 da ONU contém <b>17 Objetivos de Desenvolvimento Sustentável</b> (ODS).',a:true,e:'17 ODS: pobreza, fome, saúde, educação, igualdade de gênero, água, energia, trabalho, etc.'},
{n:65,t:'DH – Lei 13.060',q:'A Lei 13.060/2014 disciplina o uso de instrumentos de menor potencial ofensivo pelos agentes de segurança e prioriza seu uso sobre arma de fogo.',a:true,e:'Art. 2º: arma de fogo = último recurso. Prioridade para instrumentos de menor potencial ofensivo.'},
{n:66,t:'DH – Tortura',q:'O crime de tortura é equiparado a <b>hediondo</b>, sendo inafiançável e insuscetível de graça ou anistia.',a:true,e:'Art. 5º, XLIII CF: tortura = equiparado a hediondo. Lei 9.455/97.'},
{n:67,t:'DH – Refúgio',q:'O <b>non-refoulement</b> (não devolução) proíbe a deportação de refugiado para território onde sua vida esteja ameaçada.',a:true,e:'Princípio cardeal do Direito dos Refugiados. Art. 33 da Convenção de 1951.'},
{n:68,t:'DH – Deficientes',q:'A Convenção da ONU sobre PcD (2006) foi o primeiro tratado aprovado pelo rito do §3º art. 5º CF (status constitucional).',a:true,e:'Decreto 6.949/2009. Primeiro (e até agora único) tratado de DH com status de EC.'},
{n:69,t:'DH – Casos Emblemáticos',q:'No caso <b>Gomes Lund</b> (Guerrilha do Araguaia), a Corte IDH condenou o Brasil por desaparecimentos forçados durante a ditadura.',a:true,e:'Caso Gomes Lund vs Brasil (2010): desaparecimentos forçados. Brasil condenado. Lei de Anistia incompatível com CADH.'},
{n:70,t:'DH – Racismo',q:'Na CF/88, o racismo é crime <b>inafiançável e imprescritível</b>.',a:true,e:'Art. 5º, XLII CF: racismo = inafiançável + imprescritível. Diferente de hediondos (inafiançável, mas prescritível).'},

// ── ATIVIDADE DE INTELIGÊNCIA (71-90) ──
{n:71,t:'Inteligência – Conceito',q:'<b>Inteligência</b> é a atividade de obtenção, análise e disseminação de conhecimentos para assessorar o processo decisório estatal.',a:true,e:'Lei 9.883/99 e PNI: inteligência = produção de conhecimento para decisão.'},
{n:72,t:'Inteligência – Contrainteligência',q:'A <b>contrainteligência</b> tem como objetivo a <b>obtenção de informações</b> sobre ameaças externas.',a:false,e:'Contrainteligência = PROTEÇÃO de conhecimentos sensíveis e neutralização de ações adversas. Obter informações = inteligência.'},
{n:73,t:'Inteligência – SISBIN',q:'O <b>SISBIN</b> (Sistema Brasileiro de Inteligência) é coordenado pela <b>ABIN</b> e integra órgãos de diversos ministérios.',a:true,e:'Lei 9.883/99: SISBIN coordenado pela ABIN. Integra inteligência de vários órgãos federais.'},
{n:74,t:'Inteligência – PNI',q:'A Política Nacional de Inteligência (Decreto 8.793/2016) lista ameaças como espionagem, sabotagem, terrorismo e crime organizado.',a:true,e:'PNI: ameaças principais = espionagem, sabotagem, interferência externa, terrorismo, crime organizado, corrupção.'},
{n:75,t:'Inteligência – Sigilo',q:'As informações classificadas como <b>ultrassecretas</b> têm prazo máximo de sigilo de <b>25 anos</b>.',a:true,e:'LAI: reservado=5, secreto=15, ultrassecreto=25 anos. Macete: 5-15-25.'},
{n:76,t:'Inteligência – Fontes',q:'<b>OSINT</b> (Open Source Intelligence) refere-se à inteligência obtida de <b>fontes abertas</b> (públicas).',a:true,e:'OSINT = fontes abertas (jornais, internet, redes sociais). HUMINT = fontes humanas. SIGINT = sinais.'},
{n:77,t:'Inteligência – Ciclo',q:'O ciclo da inteligência compreende as fases: planejamento, reunião (coleta), análise/produção e difusão.',a:true,e:'Ciclo: planejamento → reunião → análise → difusão. Processo contínuo e dinâmico.'},
{n:78,t:'Inteligência – Operações',q:'As operações de inteligência são ações de <b>busca</b> (sigilosa) de dados negados ou não disponíveis.',a:true,e:'Busca = obtenção de dado protegido/negado. Coleta = dado disponível (fontes abertas).'},
{n:79,t:'Inteligência – ABIN',q:'A ABIN é órgão da Presidência da República e tem como missão <b>produzir conhecimentos</b> de inteligência para o Presidente.',a:true,e:'ABIN: órgão central do SISBIN, vinculado à Presidência. Produz e salvaguarda conhecimentos.'},
{n:80,t:'Inteligência – Técnicas',q:'A <b>desinformação</b> é técnica de contrainteligência que consiste em disseminar dados falsos para confundir o adversário.',a:true,e:'Desinformação: técnica de engano deliberado. Usado em contrainteligência para proteção.'},
{n:81,t:'Inteligência – Salvaguarda',q:'As <b>medidas de segurança orgânica</b> (SEGOR) abrangem segurança de pessoal, documentação, material, áreas/instalações e TI.',a:true,e:'SEGOR: pessoal + documentação + material + áreas + TI. Proteção do conhecimento sensível.'},
{n:82,t:'Inteligência – Lei 9.883',q:'A Lei 9.883/1999 instituiu o SISBIN e criou a <b>ABIN</b> como órgão central do sistema.',a:true,e:'Lei 9.883/99: cria SISBIN + ABIN. Marco legal da inteligência brasileira.'},
{n:83,t:'Inteligência – Espionagem',q:'A <b>espionagem</b> é a ação de obter informações sigilosas de outro Estado ou organização <b>sem autorização</b>.',a:true,e:'Espionagem = ameaça clássica. Obtenção clandestina de segredos de Estado.'},
{n:84,t:'Inteligência – Princípios',q:'A atividade de inteligência deve obedecer à <b>CF e às leis</b>, sendo permanente e exercida com <b>ética</b>.',a:true,e:'PNI: pressupostos incluem obediência à CF, caráter permanente, atividade de Estado, conduta ética.'},
{n:85,t:'Inteligência – Controle',q:'A atividade de inteligência no Brasil está sujeita ao controle do <b>Poder Legislativo</b> por meio da CCAI.',a:true,e:'CCAI = Comissão Mista de Controle das Atividades de Inteligência (CN). Controle externo parlamentar.'},
{n:86,t:'Inteligência – Prod. Conhecimento',q:'Os tipos de conhecimento produzidos são: <b>informe</b> (sem análise), <b>informação</b> (com análise), <b>apreciação</b> (com projeção) e <b>estimativa</b> (cenários futuros).',a:true,e:'Informe → Informação → Apreciação → Estimativa (grau crescente de elaboração).'},
{n:87,t:'Inteligência – Sabotagem',q:'A <b>sabotagem</b> é a ação deliberada para destruir ou danificar infraestruturas críticas, prejudicando o funcionamento do Estado.',a:true,e:'Sabotagem: destruição/dano de instalações, serviços ou infraestruturas. Ameaça na PNI.'},
{n:88,t:'Inteligência – SIGINT',q:'<b>SIGINT</b> (Signals Intelligence) é a inteligência obtida pela interceptação de <b>sinais e comunicações</b>.',a:true,e:'SIGINT = sinais/comunicações. COMINT = comunicações. ELINT = sinais eletrônicos.'},
{n:89,t:'Inteligência – Classificação',q:'A competência para classificar informação como <b>ultrassecreta</b> é exclusiva do Presidente da República, Vice-Presidente e Ministros de Estado.',a:true,e:'LAI, art. 27: ultrassecreta = PR, Vice, Ministros, Comandantes FA, chefes de missão diplomática. Delegável.'},
{n:90,t:'Inteligência – Crime Organizado',q:'O <b>crime organizado transnacional</b> é considerado uma das principais ameaças elencadas na PNI.',a:true,e:'PNI: crime organizado (nacional e transnacional) = ameaça. Inclui narcotráfico, contrabando, lavagem de dinheiro.'}
];
