const questions = [
    {
        "id": 481,
        "category": "Geral",
        "text": "Língua Portuguesa (Português) - Acentuação  A humanidade produz 400 milhões de toneladas de plástico por ano, e apenas 10% dele é reaproveitado, até mesmo porque a reciclagem de alguns tipos é econômica ou tecnicamente inviável. Mas pode haver solução.  Uma equipe de pesquisadores da Universidade da Califórnia, liderados pela engenheira química e ambiental Kandis Abdul-Aziz, criou um método que transforma o plástico em fertilizante: ele é misturado a palha de milho e se torna um tipo de carvão extremamente poroso, ideal para fertilizar o solo.    482)  483)  Para transformar o plástico em carvão, a equipe utiliza plásticos como o PET, empregado em garrafas, e o isopor, misturados a resíduos de milho — restos de talos, folhas, cascas e espigas. Os pesquisadores aquecem essa mistura em um reator, sem oxigênio, para romper a estrutura molecular original e obter carbono elementar, que dá origem ao carvão. Esse processo de decomposição por altas temperaturas, chamado pirólise, já é frequentemente usado com outros restos agrícolas.  Esse carvão pode aumentar o teor de nutrientes como potássio e nitrogênio no solo, além de melhorar a retenção deles. Mas uma de suas aplicações mais promissoras é o uso dele para diminuir a chamada lixiviação de nitrogênio (remoção ou dissolução desse nutriente pela ação da água sobre o solo) e aumentar o teor de carbono orgânico presente no solo, o que otimizaria sua saúde e o crescimento das plantações.  Quanto aos próximos passos para o desenvolvimento da técnica, a equipe liderada por Kandis Abdul-Aziz está pensando em combinar os plásticos com outros resíduos agrícolas comuns na Califórnia, além da palha de milho. O estado é um dos maiores produtores de frutas cítricas dos Estados Unidos da América, mas a maioria dos resíduos, como cascas, sementes e polpa, é descartada e acaba em aterros sanitários. Além de produzir uma mercadoria valiosa como o carvão, o processo desenvolvido pelos pesquisadores pode fornecer uma alternativa sustentável para elementos que geralmente são considerados lixo.  Nova tecnologia transforma plástico em adubo. Revista Superinteressante, 16/2/2023. Internet: <super.abril.com.br> (com adaptações).  Com relação à tipologia, às ideias e a aspectos linguísticos do texto precedente, julgue o item a seguir.  As palavras “pirólise” e “agrícolas” (último período do terceiro parágrafo) são acentuadas graficamente de acordo com a mesma regra de acentuação gráfica.  Certo  Errado",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 944,
        "category": "Língua Portuguesa (Português) - Orações Subordinadas Adverbiais Texto 4A4AAA A linguagem — seja ela oral ou escrita, seja mímica ou semafórica — é um sistema de símbolos, signos ou signos-símbolos, voluntariamente produzidos e 945) 946) convencionalmente aceitos, mediante o qual o ser humano se comunica com seus semelhantes, expressando suas ideias, sentimentos ou desejos. A linguagem ideal seria aquela em que cada palavra designasse apenas uma coisa, correspondesse a uma só ideia ou conceito, tivesse um só sentido. Como tal não ocorre em nenhuma língua conhecida, as palavras são, por natureza, enganosas, porque polissêmicas ou plurivalentes. Isoladas de contexto ou situação, as palavras quase nada significam de maneira precisa, inequívoca (Ogden e Richards são radicais: “as palavras nada significam por si mesmas”): “...o que determina o valor da palavra é o contexto, o qual, a despeito da variedade de sentidos de que a palavra seja suscetível, lhe impõe um valor ‘singular’; é o contexto também que a liberta de todas as representações passadas, nela acumuladas pela memória, e que lhe atribui um valor ‘atual’”. Assim, por mais condicionada que esteja a significação de uma palavra ao seu contexto, sempre subsiste nela, palavra, um núcleo significativo mais ou menos estável e constante, além de outros traços semânticos potenciais em condições de se evidenciarem nos contextos em que ela apareça. Se, como entendem Ogden e Richards, as palavras por si mesmas nada significassem, a cada novo contexto elas adquiririam significação diferente, o que tornaria praticamente impossível a própria intercomunicação linguística. Othon M. Garcia. Comunicação em Prosa Moderna . 21.ª ed. Rio de Janeiro: Editora FGV, 2002, p. 175-6 (com adaptações).",
        "text": "Considerando as relações sintático-semânticas do texto 4A4AAA, julgue o item. O vocábulo “Como” introduz no segundo período uma ideia de comparação.",
        "answer": "ERRADO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 81,
        "category": "Direito Administrativo (Doutrina e Leis Federais) - Estabilidade e Estágio Probatório",
        "text": "Julgue o item seguinte, a respeito de decadência administrativa, controle da administração pública, improbidade administrativa, aspectos relativos aos servidores públicos, conforme a Lei n.º 8.112/1990, e requisição, segundo o Decreto n.º 10.835/2021. O servidor público estável pode perder o cargo em virtude de sentença judicial transitada em julgado, bem como por meio de processo administrativo em que lhe seja assegurada ampla defesa.",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 194,
        "category": "Língua Portuguesa (Português) - Crase Texto CB1A1 Em pleno momento de grandes transformações político-sociais, na segunda metade da década de 1970, quando já havia inclinações para a volta da democracia, o cantor e compositor Belchior anunciava que “o passado é uma roupa que não nos serve mais”. Os padrões de hoje já nos estabelecem estilos e modelos diversos daqueles que 195) 196) um dia adotamos como referência. Definitivamente, aquele que envergou a vestimenta outrora usada já não é mais a mesma pessoa e qualquer tipo de tentativa de reutilizá-la passará, necessariamente, pela realização de ajustes que se amoldem ao instante presente. Velhos hábitos incorporados à nossa rotina devem, periodicamente, ser revisitados, a fim de que se tornem compatíveis com a realidade e a concretude do presente. Se, antes, a vasta cabeleira podia ser repartida ao meio, dando a quem a ostentava ares despojados e joviais, no tempo atual, para muitos, a escassez capilar obriga a adaptar o penteado. Nada adianta ficar de mal com a superfície que a imagem reflete. De qualquer forma, nada ou ninguém passa incólume pela ação do tempo, sem experimentar transformações de todas as naturezas. Mudar é verbo que se conjuga em perfeita sintonia com viver e, essencialmente, compõe rima exata com adaptar. Ao descrever a teoria da evolução, Charles Darwin assentou que a sobrevivência não é assegurada pelo emprego da força, mas depende de mudanças adaptativas dos seres expostos às transformações constantes (paulatinas ou abruptas) do ambiente que os cerca. O contexto estampado veicula um paradoxo. Se, por um lado, a marcha da mudança é via que não admite retorno, permitindo apenas momentos de variações rítmicas dos passos, mas sem nunca ser contida, por outro, ela aterroriza, chegando quase a paralisar o paciente da mutação. No entanto, não é o medo do escuro que vai impedir que a Terra gire, tampouco fará que a luz solar tome o lugar da noite pouco iluminada. Fábio Túlio Filgueiras Nogueira. O tribunal de contas contemporâneo, o processo de transformação e a pandemia. In: Edilberto Carlos Pontes Lima (coord.). Os tribunais de contas, a pandemia e o futuro do controle. Belo Horizonte: Fórum, 2021, p. 245-254 (com adaptações).",
        "text": "Julgue o item a seguir, referentes a aspectos linguísticos e ao vocabulário do texto CB1A1. A correção gramatical do texto seria mantida caso o termo “às”, em “às transformações constantes” (segundo período do terceiro parágrafo), fosse substituído por a .",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 510,
        "category": "Língua Portuguesa (Português) - Reescrita de Frases. Substituição de Palavras ou Trechos de Texto. 510) 511) Texto CG4A1 Os trabalhadores atuais estão trocando cargos de liderança por tempo livre. Um estudo realizado por uma plataforma de análise de pessoal e planejamento de força de trabalho mostra que 91% dos profissionais liberais não querem se tornar gestores de pessoas em razão das expectativas de aumento de estresse e pressão ou simplesmente por satisfação com suas funções atuais. Na pesquisa, que abrange profissionais de diferentes idades, observa-se que a tendência de equilibrar trabalho e qualidade de vida já é uma característica marcante na geração Z. Uma das mudanças que marcam essa nova geração é a liberdade, tanto no mercado de trabalho quanto na economia. Os jovens de hoje sentem-se mais confortáveis, por exemplo, em deixar o emprego após dois meses de trabalho caso a oportunidade não esteja alinhada com seus gostos pessoais e seus desejos. Também estão mais confortáveis com a economia compartilhada, preferindo alugar carros e imóveis, em vez de comprá-los. Para Marcelo Neri, professor da FGV Social, a geração Z, que abrange jovens atualmente com idade entre 14 e 29 anos, nasceu no começo da estabilidade econômica brasileira, o que pode justificar essa mentalidade mais ousada e desprendida. “A nova geração não viveu momentos de hiperinflação que eram comuns no país e que terminaram nos anos de 2010, em meio ao auge de economia”, ele afirma. Atualmente, o Brasil tem 50 milhões de jovens, o que, segundo Neri, corresponde à maior parcela populacional jovem que o país já teve, mas, segundo estudos da FGV, há expectativa de que, até o fim deste século, esse número caia para 25 milhões. Por outro lado, a geração prateada, cujos integrantes estão hoje com mais de 70 anos, está crescendo no país. Marcelo Neri afirma: “Se olharmos os padrões de vida por idade hoje, veremos que a renda dos idosos é alta em decorrência de aposentadorias, o que promete ser diferente na terceira idade da geração Z. Do jeito como está, o sistema de previdência não será tão positivo e sustentável para eles”. O professor reforça que a expectativa relacionada à fragilidade do sistema previdenciário estimula ainda mais os jovens profissionais a olharem mais para o empreendedorismo e menos para as organizações e a pensarem mais em investimentos privados que em aposentadoria.",
        "text": "Segundo ele, a geração Z é “uma população que buscará fazer a sua própria poupança e que vê na vida empreendedora ou no emprego mais flexível um futuro mais promissor”. Internet: <exame.com> (com adaptações). Julgue o item que se seguem, referentes ao vocabulário e à estrutura linguística do texto CG4A1. A reescrita do trecho “caso a oportunidade não esteja alinhada com seus gostos pessoais e seus desejos” (segundo período do parágrafo) como caso a oportunidade não esteja em consonância com o que apreciam e desejam manteria a coerência e a correção gramatical do texto.",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 483,
        "category": "Língua Portuguesa (Português) - Acentuação Texto 8A1-I O Brasil é um dos países com maior proporção de alunos matriculados em cursos de formação de professores, mas com um dos mais baixos índices de interesse na profissão. Para especialistas, isso mostra que a docência se torna opção pela facilidade em ingressar no ensino superior, pelas baixas mensalidades e pela alternativa de cursos a distância — não pela vocação. Estudos internacionais mostram que um bom professor é um dos fatores que mais influenciam na aprendizagem. Os dados são de pesquisa feita pelo Banco Interamericano de Desenvolvimento (BID), que traçou o perfil de quem estuda para ser professor na América Latina e no Caribe. Enquanto, no Brasil, 20% dos universitários estão em cursos como licenciatura e pedagogia, na América Latina são 10% e, em países desenvolvidos, 8%. Em compensação, só 5% dos jovens brasileiros dizem querer ser professores quando estão no ensino médio. E, apesar da grande quantidade de alunos matriculada em cursos de licenciatura e pedagogia no Brasil, faltam docentes para lecionar disciplinas específicas em áreas de ciências exatas e da natureza. Na Coreia do Sul, por exemplo, 21% se interessam pela profissão e só 7% ingressam, de fato, na universidade, porque há muita concorrência e maior seleção. No Chile e no México, os dois índices são mais próximos: cerca de 7% se interessam pelo magistério e menos de 15% cursam pedagogia ou licenciatura. “Muitos alunos concluintes do ensino médio entram em programas de formação de professores para conseguir um título”, diz o economista chefe da divisão de educação no BID, Gregory Elacqua. Ele afirma que isso não é bom para a educação. “A gente atrai as pessoas mais vulneráveis e que lá na frente vão enfrentar o desafio de educar crianças vulneráveis também”, diz a diretora de políticas públicas do Instituto Península, que atua na área de formação de professores, Mariana Breim. “Se é este público que está procurando a docência, temos de abraçá-lo e fazê-lo se apaixonar por ela”, completa. Os dados mostram que 71% dos estudantes de pedagogia e licenciatura no Brasil são mulheres, índice semelhante ao verificado em outros países latinos. Internet: <noticias.uol.com.br> (com adaptações).",
        "text": "Em relação a aspectos fonológicos e gráficos de vocábulos empregados no texto 8A1-I, julgue o próximo item. As palavras ‘lá’ e ‘também’, empregadas no último parágrafo, são acentuadas graficamente em razão de regras de acentuação distintas. Certo 484) 485) Errado",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 137,
        "category": "TI - Redes de Computadores - TCP e UDP",
        "text": "A respeito da arquitetura de rede TCP/IP, julgue o item a seguir. O TCP requisita que o destinatário informe, por meio do envio de um ACK ( acknowledgement ), qual foi o último pacote recebido com sucesso.",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 5,
        "category": "TI - Redes de Computadores - Windows Server 2022",
        "text": "Em relação a configurações básicas de MS Windows Server e Linux, julgue o item a seguir. No MS Windows Server, a zona DNS é uma parte específica de um namespace DNS, em que o armazenamento, por padrão, está localizado na pasta %windir%\\System32\\Dns no servidor.",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 694,
        "category": "Língua Portuguesa (Português) - Advérbio Texto CB1A1-I Desde que o almirante Pedro Álvares Cabral oficialmente descobriu a Terra de Santa Cruz, em abril de 1500, o primeiro português a estabelecer uma marca na história mineral do Brasil foi Martim Afonso de Souza. Depois de fundar a pequena vila de São Vicente, no litoral de São Paulo, a primeira base estabelecida na América portuguesa, no ano de 1531, ele tentou descobrir ouro, prata e pedras preciosas antes de sua partida para Lisboa. Esse plano visava confirmar notícias trazidas por quatro homens de sua comitiva sobre a existência de minas abundantes em ouro e prata na região do Rio Paraguai. Sob essa orientação, três expedições foram realizadas, todas em 1531: nas montanhas ao longo da costa do Rio de Janeiro, ao sul do estado de São Paulo e no Rio da Prata, mais ao sul. No entanto, as primeiras iniciativas para descoberta de metais e pedras preciosas em terras brasileiras falharam, devido às dificuldades daquela época. Apesar disso, o desejo de descobrir riquezas minerais se manteve entre os habitantes da nova colônia, estimulados pela corte portuguesa, que oferecia promessas de honra e reconhecimento para aqueles que encontrassem tais riquezas. Durante todo o século XVI, os portugueses usaram recursos financeiros, trabalho, soldados, artesãos de todos os tipos (cortadores, mineiros, construtores e até mesmo engenheiros estrangeiros) nos trabalhos de pesquisa das expedições, sob a supervisão dos governadores. Mas, infelizmente, o que foi encontrado não estava à altura do que foi despendido. Mesmo os mais positivos resultados tiveram pouco significado econômico, tanto em termos de quantidade quanto de teor dos metais. Os depósitos eram, além de pobres, localizados em lugares remotos. Concluindo, quase candidamente, que as descobertas naquele século eram desapontadoras, o governador-geral Diogo de Meneses Sequeira escreveu uma carta ao rei, afirmando que “sua Alteza precisa acreditar que as atuais minas do Brasil são compostas por açúcar e pau-brasil, muito lucrativos e com os quais o Tesouro e sua Alteza não precisam gastar um simples centavo”. Iran F. Machado e Silvia F. de M. Figueirôa. 500 anos de mineração no Brasil: breve histórico. Parte I. In: Brasil Mineral. São Paulo, n.º 186, p. 44-47, ago./2000 (com adaptações).",
        "text": "A respeito dos sentidos e dos aspectos linguísticos do texto CB1A1-I, julgue o item a seguir. No trecho “construtores e até mesmo engenheiros estrangeiros” (terceiro parágrafo), a expressão “até mesmo” está empregada com o mesmo sentido do advérbio sobretudo .",
        "answer": "ERRADO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    },
    {
        "id": 33,
        "category": "TI - Segurança da Informação - Conceitos de Certificado Digital",
        "text": "Julgue o item a seguir, a respeito de segurança, criptografia e automação. Um certificado digital do tipo A1 armazena a chave no próprio equipamento do usuário; no tipo A3, a chave é armazenada em dispositivos físicos portáteis, como tokens e cartões.",
        "answer": "CERTO",
        "explanation": "Explicação disponível no sistema Tec Concursos."
    }
];